language: cpp

os:
  - linux
  - osx
  
compiler:
  - clang

before_install:
  - git submodule update --init --recursive

before_script: echo "CC=$CXX" > make/local

matrix:
  fast_finish: true

script: ./runCmdStanTests.py src/test/interface
